# Generated by Django 5.1.15 on 2026-07-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('price_pcm', models.PositiveIntegerField(verbose_name='Rent (£ pcm)')),
                ('deposit', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('bathrooms', models.PositiveSmallIntegerField()),
                ('sqft', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sq ft')),
                ('property_type', models.CharField(choices=[('detached', 'Detached'), ('semi_detached', 'Semi-Detached'), ('terraced', 'Terraced'), ('flat', 'Flat'), ('bungalow', 'Bungalow')], default='detached', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('let_agreed', 'Let Agreed'), ('under_offer', 'Under Offer')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('available_date', models.CharField(default='Available Now', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
