# Generated by Django 5.1.15 on 2026-07-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('let_agreed', 'Let Agreed'), ('under_offer', 'Under Offer'), ('withdrawn', 'Withdrawn')], default='available', max_length=20),
        ),
    ]
