# Generated by Django 5.1.15 on 2026-07-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('hero_title', models.CharField(default='Knight & Carter', max_length=200)),
                ('hero_subtitle', models.CharField(default='Premium investment properties, handpicked for landlords.', max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
